services:
  docs-mcp-server:
    image: ghcr.io/arabold/docs-mcp-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "dist/server.js", "--protocol", "http"]
    # platform: linux/amd64
    container_name: docs-mcp-server
    ports:
      - "6280:6280"
    env_file:
      - .env
    environment:
      - MCP_PORT=6280
    volumes:
      - docs-mcp-data:/data

  docs-mcp-web:
    image: ghcr.io/arabold/docs-mcp-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "dist/web.js"]
    # platform: linux/amd64
    container_name: docs-mcp-web
    ports:
      - "6281:6281"
    env_file:
      - .env
    environment:
      - WEB_PORT=6281
    volumes:
      - docs-mcp-data:/data

volumes:
  docs-mcp-data:
    name: docs-mcp-data
